route:
 group_by: [severity, master, slave]
 receiver: opsgenie
 group_interval: 1m

receivers:
- name: opsgenie
  opsgenie_configs:
  - api_key: 5f9a4f4d-f729-48ad-9cbb-7c80111855fd
    api_url: https://api.eu.opsgenie.com/
    message: "DCOST: {{ .CommonAnnotations.SUMMARY }}"
